name: Client Crash
description: The client crashes
labels: [clientside crasher]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have searched this repository for an existing issue matching this description, and none exists. I understand this issue will be closed as a duplicate if this is not the case.
      required: true
  - type: checkboxes
    attributes:
      label: Tested platforms
      options:
        - label: Windows
        - label: OSX
        - label: Linux
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps (if known)
      description: If there are specific steps that can cause this crash, list them out here.
  - type: textarea
    attributes:
      label: Stack trace/crash report
      description: From the client-crashlog.txt or similar, show the **entire** stack trace.
    validations:
      required: true
