name: General Bug
description: A general bug within the game or code
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have searched this repository for an existing issue matching this description, and none exists. I understand this issue will be closed as a duplicate if this is not the case.
        required: true
  - type: checkboxes
    attributes:
      label: Tested platforms
      options:
      - label: Windows
      - label: OSX
      - label: Linux
  - type: textarea
    attributes:
      label: Reproduction steps (if known)
      description: If there are specific steps that can cause this crash, list them out here.
  - type: textarea
    attributes:
      label: Additional information
      description: If you have any additional information or remarks, you may put them here.
