name: Translation Error
description: A mistake in the game's translation to another language
labels: [translation error]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have searched this repository for an existing issue matching this description, and none exists. I understand this issue will be closed as a duplicate if this is not the case.
        required: true
  - type: input
    attributes:
      label: Language of the translation error
      description: Which language does this translation error occur in?
    validations:
      required: true
  - type: textarea
    attributes:
      label: The English text(s)
      description: If able, please provide the original English text(s) that are shown in this area.
  - type: textarea
    attributes:
      label: The incorrectly translated text(s)
      description: These are the text(s) that are incorrectly translated, exactly as seen in-game
    validations:
      required: true
  - type: textarea
    attributes:
      label: The correctly translated text(s)
      description: If able, you may provide corrected translations of the original English text.
  - type: textarea
    attributes:
      label: Additional information
      description: If you have any additional information or remarks, you may put them here.
